services:
  db_local:
    image: postgres:16
    container_name: coffee_shop_backend_postgres_db_local
    restart: unless-stopped
    env_file:
      - ./deployment/local/env.local
    volumes:
      - coffee_shop_local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  redis_local:
    image: redis:7
    container_name: coffee_shop_backend_redis_local
    restart: unless-stopped
    ports:
      - "6377:6379"
    environment:
      - REDIS_PASSWORD=ASJ4mdZEAF8PPYNdAzMM5SNQ81LmC0
    command: [ "redis-server", "--requirepass", "ASJ4mdZEAF8PPYNdAzMM5SNQ81LmC0" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "ASJ4mdZEAF8PPYNdAzMM5SNQ81LmC0", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  backend_local:
    container_name: coffee_shop_backend_local
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile
    ports:
      - "6000:6000"
    env_file:
      - ./deployment/local/env.local
    depends_on:
      db_local:
        condition: service_healthy
      redis_local:
        condition: service_healthy

  celery_worker_local:
    container_name: coffee_shop_backend_celery_worker_local
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile-Celery
    command: celery -A app.celery:celery worker -l info
    depends_on:
      db_local:
        condition: service_healthy
      redis_local:
        condition: service_healthy

  celery_beat_local:
    container_name: coffee_shop_backend_celery_beat_local
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile-Celery
    command: celery -A app.celery:celery beat --loglevel=info
    depends_on:
      db_local:
        condition: service_healthy
      redis_local:
        condition: service_healthy
      celery_worker_local:
        condition: service_started

  flower_local:
    container_name: coffee_shop_backend_flower_local
    build:
      context: .
      dockerfile: ./deployment/local/Dockerfile-Celery
    command: celery -A app.celery:celery flower --port=5555
    ports:
      - "3333:5555"
    depends_on:
      db_local:
        condition: service_healthy
      redis_local:
        condition: service_healthy
      celery_worker_local:
        condition: service_started

volumes:
  coffee_shop_local_postgres_data:
